/** The 22 letters of the Hebrew alphabet, in wheel display order. Final forms are never used
 * here — they only ever occur at the end of a word, and only a word's first letter matters. */
export const letters: string[] = [
  'א',
  'ב',
  'ג',
  'ד',
  'ה',
  'ו',
  'ז',
  'ח',
  'ט',
  'י',
  'כ',
  'ל',
  'מ',
  'נ',
  'ס',
  'ע',
  'פ',
  'צ',
  'ק',
  'ר',
  'ש',
  'ת',
]
