import type { LocaleStrings } from '../types'

export const strings: LocaleStrings = {
  appTitle: 'מי נשאר?',
  home: {
    newGame: 'משחק חדש',
    soloLabel: 'משחק יחיד',
    categoriesLabel: 'קטגוריות',
    scoresLabel: 'ניקוד',
    instructionsLabel: 'איך משחקים',
    settingsLabel: 'הגדרות',
  },
  setup: {
    title: 'הגדרת משחק',
    playersLabel: 'שחקנים',
    playerPlaceholder: 'שם השחקן',
    addPlayer: 'הוספת שחקן',
    removePlayer: 'הסרה',
    savedPlayersLabel: 'שחקנים שמורים',
    difficultyLabel: 'רמת קושי',
    difficultyEasy: 'קל',
    difficultyHard: 'קשה',
    difficultyMixed: 'מעורב',
    customOnlyLabel: 'רק הקטגוריות שלי',
    timerSecondsSuffix: 'שניות',
    cardsToWinLabel: 'קלפים לניצחון',
    cardsToWinSuffix: 'קלפים',
    startGame: 'התחלת משחק',
    errorTooFewPlayers: 'צריך לפחות 2 שחקנים',
    errorTooManyPlayers: 'עד 8 שחקנים במשחק',
    errorEmptyName: 'לכל שחקן צריך להיות שם',
    errorDuplicateName: 'כבר יש שחקן עם השם הזה',
    errorInvalidTimer: 'זמן התור לא תקין',
    errorInvalidCardsToWin: 'מספר הקלפים לניצחון לא תקין',
    errorNoCategories:
      'אין קטגוריות מתאימות לבחירה הזו. נסו רמת קושי אחרת או בטלו את "רק הקטגוריות שלי".',
  },
  settings: {
    title: 'הגדרות',
    soundLabel: 'צליל',
    soundOn: 'פועל',
    soundOff: 'כבוי',
    defaultTimerLabel: 'זמן ברירת מחדל לתור',
    resetData: 'איפוס נתונים שמורים',
    resetConfirm:
      'לאפס את כל הנתונים השמורים? שחקנים, ניקוד וקטגוריות מותאמות אישית יימחקו לצמיתות.',
    back: 'חזרה',
  },
  categories: {
    title: 'הקטגוריות של אלמה',
    builtInLabel: 'קטגוריות מובנות',
    customLabel: 'הקטגוריות שלי',
    textPlaceholder: 'שם הקטגוריה',
    levelLabel: 'רמה',
    addButton: 'הוספה',
    saveButton: 'שמירה',
    deleteButton: 'מחיקה',
    emptyCustom: 'עדיין אין קטגוריות מותאמות אישית',
    errorRequired: 'צריך לכתוב שם לקטגוריה',
    errorTooLong: 'שם הקטגוריה ארוך מדי (עד 40 תווים)',
    errorDuplicate: 'קטגוריה בשם הזה כבר קיימת',
    back: 'חזרה',
  },
  scores: {
    title: 'ניקוד',
    winsSuffix: 'ניצחונות',
    empty: 'עדיין אין משחקים שהסתיימו',
    soloRecordsLabel: 'שיאים במשחק יחיד',
    back: 'חזרה',
  },
  solo: {
    title: 'משחק יחיד',
    scoreLabel: 'ניקוד',
  },
  soloOver: {
    timeUpHeading: 'הזמן נגמר!',
    allLettersHeading: 'כל האותיות נמצאו!',
    scoreLabel: 'ניקוד',
    newRecord: 'שיא חדש!',
    bestScoreLabel: 'השיא שלך',
    playAgain: 'שוב',
    backHome: 'למסך הבית',
  },
  roundIntro: {
    categoryLabel: 'הקטגוריה',
    changeCategory: 'קטגוריה אחרת',
    startingPlayer: 'מתחיל/ה',
    start: 'התחלה',
  },
  gameBoard: {
    currentTurn: 'התור של',
    overtimeProgress: 'מתוך',
    quitLabel: 'יציאה',
    quitConfirm: 'לצאת מהמשחק? ההתקדמות במשחק הזה לא תישמר.',
    challengeLabel: 'פסילה',
  },
  overtimeIntro: {
    heading: 'כל האותיות נתפסו! מאפסים את הגלגל...',
  },
  playerOut: {
    heading: 'יצא/ה מהסיבוב',
    continueButton: 'המשך',
  },
  roundWon: {
    heading: 'זכה/תה בקלף',
    cardsCount: 'קלפים',
    nextRound: 'לסיבוב הבא',
  },
  gameOver: {
    heading: 'ניצח/ה במשחק',
    finalStandings: 'תוצאות סופיות',
    rematch: 'משחק חוזר',
    newGame: 'משחק חדש',
  },
  instructions: {
    title: 'איך משחקים?',
    intro:
      'המטרה: להיות האחרונים שנשארים בכל סיבוב, ולאסוף כרטיסי קטגוריה. מי שאוסף ראשון 3 כרטיסים מנצח.',
    sections: [
      {
        heading: 'לפני שמתחילים',
        body: [
          '• מוסיפים 2 עד 8 שחקנים.',
          '• בוחרים רמה: קל, קשה או מעורב.',
          '• בוחרים כמה זמן יש לכל תור: 5, 10 או 15 שניות.',
          '• בוחרים כמה כרטיסים צריך כדי לנצח: 3, 5 או 10.',
        ].join('\n'),
      },
      {
        heading: 'איך נראה סיבוב',
        body: [
          '1. מופיעה קטגוריה, למשל "מאכלים". לא אוהבים אותה? אפשר להחליף לפני שמתחילים.',
          '2. לוחצים התחל, והטיימר של השחקן הראשון מתחיל לרוץ.',
          '3. בתור שלכם אומרים בקול מילה שמתאימה לקטגוריה, ולוחצים על האות שהמילה מתחילה בה.',
          '• לדוגמה: אומרים "פיצה" ולוחצים על פ.',
          '4. האות ננעלת עד סוף הסיבוב, והתור עובר לשחקן הבא.',
          '5. לא הספקתם לפני שהטיימר נגמר? אתם בחוץ עד סוף הסיבוב.',
          '6. השחקן האחרון שנשאר זוכה בכרטיס של הקטגוריה.',
          '7. בסיבוב הבא כולם חוזרים למשחק, עם קטגוריה חדשה.',
        ].join('\n'),
      },
      {
        heading: 'חוקים חשובים',
        body: [
          '• אסור לחזור על מילה שכבר נאמרה בסיבוב.',
          '• אות נעולה אסורה. אם הצבע של האות בהיר ושקוע, מישהו כבר השתמש בה.',
          '• אותיות סופיות נחשבות כמו רגילות: ך כמו כ, ם כמו מ, ן כמו נ, ף כמו פ, ץ כמו צ.',
          '• רק האות הראשונה קובעת. לא משנה איך המילה נגמרת.',
        ].join('\n'),
      },
      {
        heading: '✋ פסילה',
        body: [
          '• אם מישהו אמר מילה שלא מתאימה, חזר על מילה או לחץ על אות לא נכונה, לוחצים על פסילה בזמן התור של השחקן שאחריו.',
          '• השחקן הקודם יוצא מהסיבוב, והאות שלו משתחררת שוב.',
        ].join('\n'),
      },
      {
        heading: '⏱️ הארכה',
        body: [
          'נגמרו כל האותיות ועדיין נשארו כמה שחקנים?',
          '• הגלגל מתאפס ומגיעה קטגוריה חדשה.',
          '• משחקים רק השחקנים שנשארו.',
        ].join('\n'),
      },
      {
        heading: '🏆 מי מנצח?',
        body: 'מי שאוסף ראשון את מספר הכרטיסים שנבחר מנצח במשחק כולו.',
      },
      {
        heading: 'משחק סולו',
        body: [
          '• משחקים לבד מול הטיימר, על קטגוריה אחת.',
          '• כל אות שלוחצים עליה מאפסת את הטיימר.',
          '• המשחק נגמר כשהזמן נגמר או כשכל 22 האותיות נוצלו.',
          '• הניקוד: כמה אותיות הספקתם. נסו לשבור את השיא שלכם!',
        ].join('\n'),
      },
    ],
    back: 'חזרה',
  },
}
